### ISSUE TITLE
about resnet

### ISSUE THREAD

**Issue by oppsAirel** [ylhz/tf_to_pytorch_model#6]
[](url)Thank you for sharing！
when source model is resnet50 or resnet101 or resnet152, the attack success rate( ASR) is has dropped significantly in the case of white-box attack.
for example, when adversarial samples are generated by Resnet50, as shown in the figure，the ASR for resnet50 is 54.2%.
![test69780983-47a9-4192-80ac-910232705995](https://user-images.githubusercontent.com/50232948/219586735-d3153fc7-1313-4230-8bb3-bbe16948945e.jpg)

**Comment by ylhz** [comment]
Hi! Thanks for your interest in our project!

Does the source model refer to the [tf_resnet_v2_50](https://github.com/ylhz/tf_to_pytorch_model/releases/download/v1.0/tf2torch_resnet_v2_50.npy) we provided, or the resnet50 in official torch?

**Comment by oppsAirel** [comment]
resnet50 in official torch.從我的iPhone傳送Shengming Yuan ***@***.***> 於 2023年2月17日 20:45 寫道：﻿
Hi! Thanks for your interest in our project!
Does the source model refer to the tf_resnet_v2_50 we provided, or the resnet50 in official torch?

**Comment by ylhz** [comment]
[ResNet v2 50](https://arxiv.org/abs/1603.05027) is a different architecture than [ResNet50](https://arxiv.org/abs/1512.03385). Therefore 54.2% is the black-box attack success rate, instead of the white-box attack success rate. 

You need to test the white-box attack success rate on ResNet50 in torch.
